# Netlify Configuration for Telegram Mini App

[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

# Production context
[context.production]
  environment = { NODE_ENV = "production" }

# Deploy preview context
[context.deploy-preview]
  environment = { NODE_ENV = "development" }

# Branch deploy context
[context.branch-deploy]
  environment = { NODE_ENV = "development" }

# Headers for security and Telegram compatibility
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    Content-Security-Policy = """
      default-src 'self';
      script-src 'self' 'unsafe-inline' https://telegram.org;
      style-src 'self' 'unsafe-inline';
      img-src 'self' data: https:;
      connect-src 'self' https://api.telegram.org https://flrts.onrender.com;
      frame-ancestors https://web.telegram.org https://*.telegram.org;
      base-uri 'self';
      form-action 'self';
    """

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# SPA redirect rule
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# API proxy (optional - if you want to proxy backend requests)
[[redirects]]
  from = "/api/*"
  to = "https://flrts.onrender.com/api/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

# Redirect www to non-www
[[redirects]]
  from = "https://www.your-domain.com/*"
  to = "https://your-domain.com/:splat"
  status = 301
  force = true

# Environment variables placeholders
[build.environment]
  VITE_TELEGRAM_BOT_TOKEN = "placeholder"
  VITE_TELEGRAM_BOT_USERNAME = "placeholder"
  VITE_API_BASE_URL = "placeholder"
  VITE_APP_URL = "placeholder"