# CodeRabbit Configuration
# Skip reviewing non-code files to reduce noise

reviews:
  # Skip documentation and config files
  path_filters:
    excluded:
      - "**/*.md"
      - "**/*.txt"
      - "**/docs/**"
      - "**/.bmad-core/**"
      - "**/LICENSE"
      - "**/.gitignore"
      - "**/package-lock.json"
      - "**/yarn.lock"
      - "**/poetry.lock"
      - "**/*.log"
      
  # Only review actual code changes
  auto_review:
    enabled: true
    # Skip drafts and WIP
    ignore_title_patterns:
      - "WIP"
      - "DO NOT MERGE"
      - "DRAFT"
      
# Keep reviews focused on code quality
chat:
  auto_reply: false  # Don't auto-reply to every comment