# Pre-commit hooks that auto-fix instead of just complaining
# Run: pre-commit install
# Then commits will auto-format your code

repos:
  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black
        language_version: python3.11
        args: ['--quiet']  # Don't show files being formatted

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.0
    hooks:
      - id: ruff
        args: ['--fix', '--exit-zero']  # Fix what we can, never fail
      - id: ruff-format  # Use ruff's formatter (faster than black)

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        args: ['--markdown-linebreak-ext=md']
      - id: end-of-file-fixer
        exclude: '\.svg$|\.png$|\.jpg$'
      - id: check-yaml
        exclude: 'cloudformation/.*'
      - id: check-added-large-files
        args: ['--maxkb=1000']
      - id: check-merge-conflict

# Don't run on CI - these are developer tools
ci:
  skip: [black, ruff, ruff-format]