services:
  - type: web
    name: BrainBot
    env: python
    repo: git@github.com:auldsyababua/BrainBot.git
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host=0.0.0.0 --port=10000
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
    plan: free
    autoDeploy: true
    env: python
    healthCheckPath: /