services:
  - type: web
    name: markdown-brain-bot
    runtime: python
    region: oregon
    plan: starter
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python webhook_server.py"
    healthCheckPath: /
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: S3_ACCESS_KEY_ID
        sync: false
      - key: S3_SECRET_ACCESS_KEY
        sync: false
      - key: S3_BUCKET_NAME
        value: "markdown-brain-bot"
      - key: S3_REGION
        value: "us-east-1"
      - key: S3_ENDPOINT_URL
        sync: false
    autoDeploy: false