services:
  - type: worker
    name: BrainBot
    env: python
    repo: git@github.com:auldsyababua/BrainBot.git
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: python main_polling.py
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: UPSTASH_REDIS_REST_URL
        sync: false
      - key: UPSTASH_REDIS_REST_TOKEN
        sync: false
      - key: UPSTASH_VECTOR_REST_URL
        sync: false
      - key: UPSTASH_VECTOR_REST_TOKEN
        sync: false
      - key: VECTOR_NAMESPACE
        value: "10netzero"
      - key: VECTOR_TOP_K
        value: "5"
    plan: free
    autoDeploy: true