#!/bin/bash

echo "🔧 Render Configuration Checker"
echo "==============================="

echo ""
echo "📋 Required Environment Variables for Render:"
echo "--------------------------------------------"
echo "✅ TELEGRAM_BOT_TOKEN"
echo "✅ OPENAI_API_KEY" 
echo "✅ SUPABASE_URL"
echo "✅ SUPABASE_KEY"
echo "✅ UPSTASH_REDIS_URL"
echo "✅ UPSTASH_REDIS_TOKEN"
echo "✅ UPSTASH_VECTOR_REST_URL"
echo "✅ UPSTASH_VECTOR_REST_TOKEN"
echo "✅ CF_PROXY_SECRET (must match consumer worker)"
echo "✅ PORT (should be auto-set by Render)"

echo ""
echo "📋 Required Render Service Settings:"
echo "-----------------------------------"
echo "✅ Build Command: pip install -r requirements.txt"
echo "✅ Start Command: python main.py"
echo "✅ Environment: Python 3.11+"
echo "✅ Service Type: Web Service"
echo "✅ Port: 8000 (or auto-detected)"

echo ""
echo "🔍 Common Issues:"
echo "----------------"
echo "❌ Missing CF_PROXY_SECRET environment variable"
echo "❌ Wrong Python version (needs 3.9+)"
echo "❌ Missing dependencies in requirements.txt"
echo "❌ main.py not in root directory"
echo "❌ Port binding issues (should use PORT env var)"

echo ""
echo "🚨 Check Render Dashboard:"
echo "-------------------------"
echo "1. Go to https://dashboard.render.com"
echo "2. Find your brainbot service"
echo "3. Check 'Logs' tab for errors"
echo "4. Verify 'Environment' tab has all variables"
echo "5. Check 'Settings' for build/start commands"

echo ""
echo "🔧 Quick Fix Commands:"
echo "---------------------"
echo "# If service is failing, try manual deploy:"
echo "# 1. Go to Render dashboard"
echo "# 2. Click 'Manual Deploy' → 'Deploy latest commit'"
echo ""
echo "# If environment variables are missing:"
echo "# 1. Go to Environment tab in Render"
echo "# 2. Add missing variables from your .env file"