name = "brainbot-consumer"
main = "src/consumer.ts"
compatibility_date = "2024-08-01"

[[queues.consumers]]
queue = "brainbot-updates"

[[kv_namespaces]]
binding = "BRAINBOT_KV"
id = "406b3a3a56cb448fa62e9fa032c6a4a6"

[[r2_buckets]]
binding = "BRAINBOT_MEDIA"
bucket_name = "brainbot-media"

[[vectorize]]
binding = "VECTORIZE"
index_name = "brainbot-docs"

[vars]
PROCESS_URL = "https://brainbot-v76n.onrender.com/process"
AIGW_URL = "https://gateway.ai.cloudflare.com/v1/<account>/<brainbot-gw>"
AIGW_PROVIDER = "openai"

[observability]
enabled = true
