name = "brainbot-webhook"
main = "src/webhook.ts"
compatibility_date = "2024-08-01"

routes = [] # add your route in Cloudflare dashboard or via wrangler

[vars]
# Set these in Cloudflare dashboard or wrangler secrets
TELEGRAM_WEBHOOK_SECRET = ""
CF_PROXY_SECRET = ""

[[queues.producers]]
queue = "brainbot-updates"
binding = "UPDATES"

[[kv_namespaces]]
binding = "BRAINBOT_KV"
id = "brainbot-kv"

[[r2_buckets]]
binding = "BRAINBOT_MEDIA"
bucket_name = "brainbot-media"

[vectorize]
binding = "VZ"
index_name = "brainbot-docs"

[ai]
binding = "AI"

[observability]
enabled = true

