name: Enforce Linear Issue in PR Title

on:
  pull_request_target:
    types: [opened, edited, synchronize, reopened]

jobs:
  check-pr-title:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    
    steps:
      - name: Check PR title format
        id: check-title
        uses: actions/github-script@v7
        with:
          script: |
            const prTitle = context.payload.pull_request.title;
            const pattern = /^10N-\d+:/;
            
            if (!pattern.test(prTitle)) {
              const errorMessage = `❌ PR title must start with a Linear issue ID\n\n` +
                `**Expected format:** \`10N-123: Your PR title\`\n` +
                `**Current title:** \`${prTitle}\`\n\n` +
                `Please update your PR title to include the Linear issue ID at the beginning.`;
              
              // Post comment if title is invalid
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body: errorMessage
              });
              
              // Set status check to failed
              await github.rest.repos.createCommitStatus({
                owner: context.repo.owner,
                repo: context.repo.repo,
                sha: context.payload.pull_request.head.sha,
                state: 'failure',
                target_url: 'https://linear.app/10netzero/issues',
                description: 'PR title must include Linear issue ID (10N-XXX)',
                context: 'linear/pr-title'
              });
              
              core.setFailed('PR title must include Linear issue ID in format: 10N-123: description');
            } else {
              // Extract issue ID for output
              const issueId = prTitle.match(/10N-\d+/)[0];
              core.setOutput('linear_issue_id', issueId);
              
              // Set status check to success
              await github.rest.repos.createCommitStatus({
                owner: context.repo.owner,
                repo: context.repo.repo,
                sha: context.payload.pull_request.head.sha,
                state: 'success',
                target_url: `https://linear.app/10netzero/issue/${issueId}`,
                description: `Linked to Linear issue ${issueId}`,
                context: 'linear/pr-title'
              });
              
              console.log(`✅ PR title contains Linear issue ID: ${issueId}`);
            }