name: Test Self-Hosted Runner

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize]

jobs:
  test:
    runs-on: [self-hosted, macOS, ARM64]
    
    steps:
      - uses: actions/checkout@v4
      
      - name: System Info
        run: |
          echo "Runner: $(hostname)"
          echo "OS: $(uname -a)"
          echo "Python: $(python3 --version)"
          
      - name: Set up Python
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          
      - name: Install dependencies
        run: |
          source venv/bin/activate
          pip install -r requirements.txt
          pip install black ruff mypy pytest pytest-asyncio
          
      - name: Run Black
        run: |
          source venv/bin/activate
          black --check src/ tests/ main.py
          
      # - name: Run Ruff
      #   run: |
      #     source venv/bin/activate
      #     ruff check
      # Temporarily disabled - has import issues in integration tests
          
      - name: Run Tests
        env:
          TELEGRAM_BOT_TOKEN: "test-token-not-real"
          SUPABASE_URL: "https://test.supabase.co"
          SUPABASE_KEY: "test-key-not-real"
          OPENAI_API_KEY: "sk-test-not-real"
          NEO4J_URI: "bolt://localhost:7687"
          NEO4J_USER: "neo4j"
          NEO4J_PASSWORD: "test-password"
          CLOUDFLARE_ACCOUNT_ID: "test-account-id"
          CLOUDFLARE_API_TOKEN: "test-api-token"
          CLOUDFLARE_KV_NAMESPACE_ID: "test-namespace-id"
        run: |
          source venv/bin/activate
          python -m pytest tests/unit/ -v --tb=short
          
      - name: Cleanup
        if: always()
        run: rm -rf venv